Update File_Dir for 3.2.2
thomas-rcv/admidio-written_communications pull request #9
Opened 2017-01-03 14:45 UTC by M4-CP

2017-01-03 15:44 UTC, Fasse requested changes

2017-01-03 15:44 UTC, Fasse commented on written_communications.php
> +if(is_dir('../../adm_my_files/download_clb/MSWord_Templates'))
**download_clb** is your specific download folder. Use `TableFolder::getRootFolderName()` to get the organization specific download folder.

e.g.
`'../../adm_my_files/'. TableFolder::getRootFolderName() .'/MSWord_Templates'`

2017-01-03 15:44 UTC, Fasse commented on written_communications.php
> +    $dir = '../../adm_my_files/download_clb/MSWord_Templates';
**download_clb** is your specific download folder. Use `TableFolder::getRootFolderName()` to get the organization specific download folder.

e.g.
`'../../adm_my_files/'. TableFolder::getRootFolderName() .'/MSWord_Templates'`

2017-01-09 14:38 UTC, thomas-rcv commented
Already implemented in Version 3.1
Will close this pull request

2017-01-09 14:39 UTC, closed without merging